---
# Enabled --> Configure
- name:   Enable and Start
  ufw:
    state: enabled
  when:   firewall_enabled == true

# Disabled
- name:   Disable
  ufw:
    state: disabled
  when:   firewall_enabled == false
